### PR TITLE
Fully support POST: enforceLabel/matcher/labelAPI (#55)

### LINKED ISSUE #55: Grafana alert is not working as expected with Prom-Label-Proxy
Grafana alert evaluation is not happening correctly when using Prom-Label-Proxy.

Current architecture:
Grafana -> nginx -> prom-label-proxy -> cortex frontend -> thanos querier -> Prometheus

**Issue:**
Using nginx to add the label and value as query param in every requests. This is working for all dashboards and the data is showing correctly. However, the alert evaluation is not happening correctly and always showing in alerting status.

When I click the "Test Rule" from Grafana alert configuration, I can see the below error response.
```
Object
firing:true
state:"pending"
conditionEvals:" = true"
timeMs:"62.522ms"
error:"tsdb.HandleRequest() error server_error: server error: 502"
logs:Array[1]
0:Object
message:"Condition[0]: Query"
data:Object
```

### PR DESCRIPTION
**Pull request by hanjm**
Closes #55

Grafana always use POST when grafana alert query Prometheus ref: [grafana code](https://github.com/grafana/grafana/blob/main/pkg/tsdb/prometheus/prometheus.go#L89) , [prometheus client_golang code](https://github.com/prometheus/client_golang/blob/master/api/prometheus/v1/api.go#L1101)

Grafana 8.0 default use POST in Prometheus datasource. ref: [grafana#34599](https://github.com/grafana/grafana/pull/34599)

Current, `prom-label-proxy` cannot proxy POST method correctly.  

```
 go run main.go  -label namespace -upstream http://127.0.0.1:9090 -insecure-listen-address :29192 -enable-label-apis -unsafe-passthrough-paths /api/v1/metadata,/api/v1/query_exemplars
```

main/master branch:
image
image

this PR fixed it, make `prom-label-proxy` proxy POST method correctly: 
image

hi @bwplotka  @s-urbaniak Could you help review? thank you :)

### CODE REVIEW

File: injectproxy/routes.go [hunk 1]
```diff
@@ -338,7 +352,15 @@ func (r *routes) matcher(w http.ResponseWriter, req *http.Request) {
...
 
-	req.URL.RawQuery = q.Encode()
+	if req.Method == http.MethodPost {
+		// We are replacing request body, close previous one (ParseForm ensures it is read fully and not nil).
+		_ = req.Body.Close()
+		newBody := q.Encode()
+		req.Body = ioutil.NopCloser(strings.NewReader(newBody))
+		req.ContentLength = int64(len(newBody))
+	} else {
+		req.URL.RawQuery = q.Encode()
```
[the remark this answers is not in the document]
Comment (hanjm) [reply injectproxy/routes.go]: You are right, let me fix it.

**Comment by hanjm** [comment]
Done rebase master.

**Review by simonpasquier — APPROVED** [review]
lgtm, thanks!
I'll wait a bit to ensure that the changes are ok for @squat too.

File: injectproxy/routes.go [hunk 2]
```diff
@@ -206,8 +206,23 @@ func (r *routes) enforceLabel(h http.HandlerFunc) http.Handler {
...
 		// Remove the proxy label from the query parameters.
 		q := req.URL.Query()
-		q.Del(r.label)
+		if q.Get(r.label) != "" {
+			q.Del(r.label)
+		}
 		req.URL.RawQuery = q.Encode()
+		// Remove the proxy label from the form.
+		if req.Form.Get(r.label) != "" {
+			req.Form.Del(r.label)
```
Comment (squat) [inline injectproxy/routes.go:215]: This doesn't actually do anything, right? This form is not re-encoded anywhere or used anywhere else, no?

**Review by squat — CHANGES_REQUESTED** [review]
I think there is something funny with deleting the value from the `req.Form`. PTAL

File: injectproxy/routes.go (hunk 2 above)
Comment (hanjm) [reply injectproxy/routes.go]: right. let me remove it.

**Review by squat — APPROVED** [review]
Lgtm :) thanks for the contribution
